server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bxly-tourist?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    url: jdbc:mysql://139.199.89.142:3306/bxkazlka?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    url: jdbc:mysql://139.199.72.118:3306/bxkazlka?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root123
#    password: bx123@@
#    password: "@bx123456"
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
## 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.bxly.toursts.model
